# Generated by Django 3.2.13 on 2023-11-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='task_answer',
        ),
        migrations.AddField(
            model_name='result',
            name='time',
            field=models.TextField(default='00:00', null=True),
        ),
    ]
